global:
  defaultStorageClass: "nfs-client"

auth:
  user: "admin"
  password: "geoserver!araG1S"

architecture: replication

extraEnvVars:
  - name: DB_LOWRES
    value: "osm_lowres"
  - name: DB_EXTRAS
    value: "osm_extras"
  - name: DB_GWC
    value: "osm_gwc"

initialMemory: "10G"
maximumMemory: "20G"
diskQuotaSize: "1000"
stableExtensions: "css-plugin,feature-pregeneralized-plugin,web-resource-plugin"
fontsDir: "/opt/geoserver/data_dir/fonts"

primary:
  resourcesPreset: "none"
  resources: {}
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  startupProbe:
    enabled: false
  service:
    type: NodePort
    nodePorts:
      http: "31080"

secondary:
  replicaCount: 1
  resourcesPreset: "none"
  resources: {}
  service:
    type: NodePort
    nodePorts:
      http: ""
  autoscaling:
    hpa:
      enabled: false


persistence:
  geoserverDataDir:
    enabled: true
    existingClaim: "geo-basemaps-geoserver-geoserver-data-dir"
  geowebcacheCacheDir:
    enabled: true
    existingClaim: "geo-basemaps-geoserver-geowebcache-cache-dir"

externalDatabase:
  host: "db-postgresql-primary"
  user: postgres
  password: ""
  existingSecret: "db-postgresql"
  existingSecretPasswordKey: "postgres-password"
  database: osm
  port: 5432