global:
  defaultStorageClass: "nfs-client"

auth:
  user: "admin"
  password: "geoserver!araG1S"

architecture: replication

extraEnvVars:
  - name: DB_LOWRES
    value: "osm_lowres"
  - name: DB_EXTRAS
    value: "osm_extras"
  - name: DB_GWC
    value: "osm_gwc"

initialMemory: "10G"
maximumMemory: "20G"
stableExtensions: "css-plugin,feature-pregeneralized-plugin,web-resource-plugin"

primary:
  resourcesPreset: "none"
  resources: {}
  service:
    type: NodePort
    nodePorts:
      http: "31080"

secondary:
  replicaCount: 1
  resourcesPreset: "none"
  resources: {}
  service:
    type: NodePort
    nodePorts:
      http: ""

persistence:
  geoserverDataDir:
    enabled: true
    existingClaim: ""
  geowebcacheCacheDir:
    enabled: true
    existingClaim: ""

externalDatabase:
  host: "db-postgresql-primary"
  user: postgres
  password: ""
  existingSecret: "db-postgresql"
  existingSecretPasswordKey: "postgres-password"
  database: test-geoserver
  port: 5432
