apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-db
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: geoserver
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  # ####################################################################
  # Database Env variables
  # ##################################################################### 
  POSTGRES_HOST: ""
  POSTGRES_PORT: "5432"
  POSTGRES_USER: ""
  POSTGRES_PASS: ""
  POSTGRES_DB: ""