{{- if and .Values.persistence.geoserverDataDir.enabled (not .Values.persistence.geoserverDataDir.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:  
  name: {{ printf "%s-geoserver-data-dir" (include "common.names.fullname" .) }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.persistence.geoserverDataDir.labels .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: geoserver
  {{- if .Values.persistence.geoserverDataDir.annotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.geoserverDataDir.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.geoserverDataDir.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- if .Values.persistence.geoserverDataDir.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.geoserverDataDir.dataSource "context" $) | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.geoserverDataDir.size | quote }}
  {{- if .Values.persistence.geoserverDataDir.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.geoserverDataDir.selector "context" $) | nindent 4 }}
  {{- end }}
  {{- include "common.storage.class" (dict "persistence" .Values.persistence.geoserverDataDir "global" .Values.global) | nindent 2 }}
{{- end -}}
{{- if and .Values.persistence.geowebcacheCacheDir.enabled (not .Values.persistence.geowebcacheCacheDir.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-geowebcache-cache-dir" (include "common.names.fullname" .) }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.persistence.geowebcacheCacheDir.labels .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: geoserver
  {{- if .Values.persistence.geowebcacheCacheDir.annotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.geowebcacheCacheDir.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.geowebcacheCacheDir.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- if .Values.persistence.geowebcacheCacheDir.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.geowebcacheCacheDir.dataSource "context" $) | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.geowebcacheCacheDir.size | quote }}
  {{- if .Values.persistence.geowebcacheCacheDir.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.geowebcacheCacheDir.selector "context" $) | nindent 4 }}
  {{- end }}
  {{- include "common.storage.class" (dict "persistence" .Values.persistence.geowebcacheCacheDir "global" .Values.global) | nindent 2 }}
{{- end -}}
