apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pelias-data
  namespace: gtelmaps
  labels:
    app.kubernetes.io/instance: pelias
    app.kubernetes.io/name: pelias
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client