diagnosticMode:
  enabled: false

api:
  service:
    type: NodePort

libpostal:
  enabled: true
  service:
    type: NodePort

interpolation:
  enabled: true
  service:
    type: NodePort

pip:
  enabled: true
  service:
    type: NodePort

placeholder:
  enabled: true
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  service:
    type: NodePort

persistence:
  existingClaim: "pelias-data"