diagnosticMode:
  enabled: false

initJob:
  elasticCreateIndex:
    enabled: false
  downloadData:
    enabled: false
  prepareData:
    enabled: false
  importData:
    enabled: false

  cleanupAfterFinished:
    enabled: true
    seconds: 120

api:
  service:
    type: NodePort

libpostal:
  enabled: true
  service:
    type: NodePort

interpolation:
  enabled: true
  service:
    type: NodePort

pip:
  enabled: true
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  service:
    type: NodePort

placeholder:
  enabled: true
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  service:
    type: NodePort

persistence:
  existingClaim: "pelias-data"