{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.libpostal.enabled }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "pelias.libpostal.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: pelias
    app.kubernetes.io/component: libpostal
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.libpostal.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/part-of: pelias
      app.kubernetes.io/component: libpostal
  {{- if not .Values.libpostal.autoscaling.hpa.enabled }}
  replicas: {{ .Values.libpostal.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimitCount }}
  {{- if .Values.libpostal.updateStrategy }}
  strategy: {{- toYaml .Values.libpostal.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/part-of: pelias
        app.kubernetes.io/component: libpostal
      annotations:
        {{- if .Values.libpostal.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "pelias.libpostal.imagePullSecrets" . | nindent 6 }}
      automountServiceAccountToken: {{ .Values.libpostal.automountServiceAccountToken }}
      {{- if .Values.libpostal.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.libpostal.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.libpostal.podAffinityPreset "component" "libpostal" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.libpostal.podAntiAffinityPreset "component" "libpostal" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.libpostal.nodeAffinityPreset.type "key" .Values.libpostal.nodeAffinityPreset.key "values" .Values.libpostal.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.libpostal.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.libpostal.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.libpostal.priorityClassName }}
      priorityClassName: {{ .Values.libpostal.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.libpostal.schedulerName }}
      schedulerName: {{ .Values.libpostal.schedulerName }}
      {{- end }}
      {{- if .Values.libpostal.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.libpostal.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pelias.libpostal.serviceAccountName" . }}
      {{- if .Values.libpostal.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.libpostal.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.libpostal.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.initContainers "context" $) | trim | nindent 8 }}
        {{- end }}
        {{- if .Values.libpostal.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.initContainers "context" $) | trim | nindent 8 }}
        {{- end }}
      containers:
        - name: pelias-libpostal
          image: {{ include "pelias.libpostal.image" . }}
          imagePullPolicy: {{ .Values.libpostal.image.pullPolicy }}          
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.libpostal.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.libpostal.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.libpostal.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.libpostal.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
            {{- if .Values.libpostal.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if or .Values.libpostal.extraEnvVarsCM .Values.libpostal.extraEnvVarsSecret .Values.libpostal.extraEnvVarsSecrets .Values.extraEnvVarsCM .Values.extraEnvVarsSecret .Values.extraEnvVarsSecrets }}
          envFrom:
            {{- if .Values.extraEnvVarsCM }}
            - configMapRef:
                name: {{ .Values.extraEnvVarsCM }}
            {{- end }}
            {{- if .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.extraEnvVarsSecret }}
            {{- end }}
            {{- if .Values.libpostal.extraEnvVarsCM }}
            - configMapRef:
                name: {{ .Values.libpostal.extraEnvVarsCM }}
            {{- end }}
            {{- if .Values.libpostal.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.libpostal.extraEnvVarsSecret }}
            {{- end }}
            {{- if .Values.extraEnvVarsSecrets }}
            {{- range .Values.extraEnvVarsSecrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
            {{- if .Values.libpostal.extraEnvVarsSecrets }}
            {{- range .Values.libpostal.extraEnvVarsSecrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.libpostal.containerPorts.http }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.libpostal.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.libpostal.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.libpostal.startupProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: http
          {{- end }}
          {{- if .Values.libpostal.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.libpostal.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.libpostal.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /parse?address=47A Phạm Viết Chánh, Phường Nguyễn Cư Trinh, Quận 1, Thành phố Hồ Chí Minh, Việt Nam
              port: http
          {{- end }}
          {{- if .Values.libpostal.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.libpostal.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.libpostal.readinessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: http
          {{- end }}
          {{- end }}
          {{- if .Values.libpostal.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.libpostal.resources }}
          resources: {{- toYaml .Values.libpostal.resources | nindent 12 }}
          {{- else if ne .Values.libpostal.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.libpostal.resourcesPreset) | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
            {{- if .Values.libpostal.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.sidecars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.sidecars "context" $) | trim | nindent 8 }}
        {{- end }}
        {{- if .Values.libpostal.sidecars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.sidecars "context" $) | trim | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.libpostal.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.libpostal.extraVolumes "context" $) | nindent 8 }}
        {{- end }}   
{{- end }}