{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.initJob.importData.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-import-data" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: pelias
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.initJob.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
spec:
  backoffLimit: {{ .Values.initJob.backoffLimit }}
  {{- if .Values.initJob.cleanupAfterFinished.enabled }} 
  ttlSecondsAfterFinished: {{ .Values.initJob.cleanupAfterFinished.seconds }} 
  {{- end }} 
  template:
    metadata:
      {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.initJob.podLabels .Values.commonLabels ) "context" . ) }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
      {{- if .Values.initJob.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.initJob.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      {{- include "pelias.api.imagePullSecrets" . | nindent 6 }}
      restartPolicy: OnFailure
      {{- if .Values.initJob.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.initJob.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.initJob.importData.whosonfirst.enabled }}
        - name: import-whosonfirst
          image: pelias/whosonfirst:master
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -ec
            - |
              [ ! -f "/data/tmp/import_whosonfirst.lock" ] && ./bin/start && install -D /dev/null /data/tmp/import_whosonfirst.lock || echo "Done!"
          volumeMounts:
            - name: configuration
              mountPath: /code/pelias.json
              subPath: pelias.json
            - name: data
              mountPath: /data
        {{- end }}
        {{- if .Values.initJob.importData.openaddresses.enabled }}
        - name: import-openaddresses
          image: pelias/openaddresses:master
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -ec
            - |
              [ ! -f "/data/tmp/import_openaddresses.lock" ] && ./bin/parallel ${OPENADDRESSES_PARALLELISM:-1} && install -D /dev/null /data/tmp/import_openaddresses.lock || echo "Done!"
          volumeMounts:
            - name: configuration
              mountPath: /code/pelias.json
              subPath: pelias.json
            - name: data
              mountPath: /data
        {{- end }}
        {{- if .Values.initJob.importData.openstreetmap.enabled }}
        - name: import-openstreetmap
          image: pelias/openstreetmap:master
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -ec
            - |
              [ ! -f "/data/tmp/import_openstreetmap.lock" ] && ./bin/start && install -D /dev/null /data/tmp/import_openstreetmap.lock || echo "Done!"
          volumeMounts:
            - name: configuration
              mountPath: /code/pelias.json
              subPath: pelias.json
            - name: data
              mountPath: /data
        {{- end }}
        {{- if .Values.initJob.importData.polylines.enabled }}
        - name: import-polylines
          image: pelias/polylines:master
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -ec
            - |
              [ ! -f "/data/tmp/import_polylines.lock" ] && ./bin/start && install -D /dev/null /data/tmp/import_polylines.lock || echo "Done!"
          volumeMounts:
            - name: configuration
              mountPath: /code/pelias.json
              subPath: pelias.json
            - name: data
              mountPath: /data
        {{- end }}
        {{- if .Values.initJob.importData.geonames.enabled }}
        - name: import-geonames
          image: pelias/geonames:master
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -ec
            - |
              [ ! -f "/data/tmp/import_geonames.lock" ] && ./bin/start && install -D /dev/null /data/tmp/import_geonames.lock || echo "Done!"
          volumeMounts:
            - name: configuration
              mountPath: /code/pelias.json
              subPath: pelias.json
            - name: data
              mountPath: /data
        {{- end }}
        {{- if .Values.initJob.importData.transit.enabled }}
        - name: import-transit
          image: pelias/transit:master
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -ec
            - |
              [ ! -f "/data/tmp/import_transit.lock" ] && ./bin/start && install -D /dev/null /data/tmp/import_transit.lock || echo "Done!"
          volumeMounts:
            - name: configuration
              mountPath: /code/pelias.json
              subPath: pelias.json
            - name: data
              mountPath: /data
        {{- end }}
        {{- if .Values.initJob.importData.csv.enabled }}
        - name: import-csv
          image: pelias/csv-importer:master
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -ec
            - |
              [ ! -f "/data/tmp/import_csv.lock" ] && ./bin/parallel ${CSV_PARALLELISM:-1} && install -D /dev/null /data/tmp/import_csv.lock || echo "Done!"
          volumeMounts:
            - name: configuration
              mountPath: /code/pelias.json
              subPath: pelias.json
            - name: data
              mountPath: /data
          {{- end }}
      containers:
        - name: import-final
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "echo 'Job completed!'"]
      volumes:
        - name: configuration
          configMap:
            name: {{ include "pelias.configMapName"  . }}
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "common.names.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}